--INSERT INTO STAND (Nome, Endereco, Telefone, Email)
--VALUES ('Concessionária de Lisboa ', 'Rua das Flores, 123, 1200-001, Lisboa, Portugal', '210123456', 'concessionariaLisboa@stand.pt'),
--       ('Concessionária de Porto ', 'Avenida da Liberdade, 456, 4000-009, Porto, Portugal', '220987654', 'concessionariaPorto@stand.pt'),
--       ('Concessionária de Faro ', 'Travessa do Forno, 789, 8000-070, Faro, Portugal', '289543210', 'concessionariaFaro@stand.pt'),
--       ('Concessionária de Coimbra', 'Praça 8 de Maio, 321, 3000-300, Coimbra, Portugal', '239876543', 'concessionariaCoimbra@stand.pt');

--INSERT INTO STAND_MarcasCarros (Marca)
--VALUES
--('Audi'),
--('BMW'),
--('Mercedes-Benz'),
--('Volkswagen'),
--('Porsche'),
--('Ferrari'),
--('Lamborghini'),
--('Bugatti'),
--('Ford'),
--('Chevrolet'),
--('Toyota'),
--('Honda'),
--('Nissan'),
--('Mazda'),
--('Subaru'),
--('Hyundai'),
--('Kia'),
--('Tesla'),
--('Peugeot'),
--('Renault'),
--('Citroën'),
--('Opel'),
--('Alfa Romeo'),
--('Fiat'),
--('Volvo'),
--('Skoda'),
--('Seat'),
--('Lexus'),
--('Land Rover'),
--('Aston Martin')

-- INSERT INTO STAND_FuncaoStand (Funcao)
-- VALUES
-- ('Gerente de Stand'),
-- ('Vendedor de Automóveis'),
-- ('Consultor Financeiro'),
-- ('Técnico de Manutenção/Serviço'),
-- ('Recepcionista'),
-- ('Gestor de Peças'),
-- ('Gerente de Marketing e Publicidade'),
-- ('Limpeza e Preparação de Veículos');



--INSERT INTO STAND_CorVeiculo( Cor)
--VALUES
--('Preto'),
--('Branco'),
--('Vermelho'),
--('Azul'),
--('Verde'),
--('Cinza'),
--('Amarelo'),
--('Prata'),
--('Bege'),
--('Castanho')


--INSERT INTO STAND_CategoriaVeiculos( Categoria)
--VALUES
--('Ligeiro'),
--('Comercial'),
--('Pesado'),
--('Motociclo'),
--('Quadriciclo Pesado'),
--('SUV/4x4'),
--('VAN/Minivan')

-- INSERT INTO STAND_Combustiveis (Combustivel)
-- VALUES
-- ('Gasolina'),
-- ('Diesel'),
-- ('Elétrico'),
-- ('Híbrido'),
-- ('Gás Natural'),
-- ('Hidrogénio');
